### ISSUE TITLE
after entering number have this issue

### ISSUE THREAD

**Issue by SportsUnity** [Ahlyab/Udemy-coupon-fetcher.github.io#2]
Traceback (most recent call last):
  File "Udemy Free Coupons.py", line 72, in <module>
  File "Udemy Free Coupons.py", line 31, in get_coupon_link_from_list
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 462, in find_element_by_partial_link_text
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: https://www.udemy.com/

**Comment by Prakash2006-chems** [comment]
Hi,

I am receving the below error :-

[+] Work in Progress!
Traceback (most recent call last):
  File "Udemy Free Coupons.py", line 62, in <module>
  File "Udemy Free Coupons.py", line 32, in get_coupon_link_from_list
  File "selenium\webdriver\remote\webelement.py", line 80, in click
  File "selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: Element <a class="ui big inverted green button discBtn" href="https://www.discudemy.com/go/hr-budgeting-mastery-plan-forecast-justify-hr-costs"> is not clickable at point (789,658) because another element <iframe id="aswift_6" name="aswift_6" src="https://googleads.g.doubleclick.net/pagead/html/r20250513/r20190131/zrt_lookup_fy2021.html#RS-1-&adk=1812271801&client=ca-pub-4527724209556572&fa=1&ifi=7&uci=a!7&btvi=4"> obscures it

[24032] Failed to execute script Udemy Free Coupons

**Comment by Ahlyab** [comment]
@Prakash2006-chems thanks for the feedback. it's been a while I haven't updated the app. I will update it and let you know

**Comment by Prakash2006-chems** [comment]
Hi Ahlyab,

Thank you.

**Comment by Prakash2006-chems** [comment]
Hi,

Any update on the same

**Comment by Prakash2006-chems** [comment]
Hi,

Any update on the same
